project:
  type: book
  output-dir: _book

book:
  title: "金融数据获取、管理与初步分析"
  subtitle: "基于CAPM模型的A股实证研究"
  author: "PYC1234"
  date: "2026-04-07"
  repo-url: "https://github.com/PYC1234/dshw-p02"
  repo-actions: [issue]

  sidebar:    # 侧边栏配置
    #title: "金融数据获取、管理与初步分析"
    logo: images/book-logo.png
    style: floating  #docked
    search: true

  # favicon: images/book-logo.png   # URL logo
  # site-url: https://pyc1234.github.io/dshw-p02/ 
  # editor: source    # 始终采用源代码模式编辑

  chapters:
    - index.qmd
    - 01_download.ipynb
    - 02_clean.ipynb
    - 03_regression_analysis.ipynb
    - 04_capm_analysis.ipynb

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false   #用于章节编号
    anchor-sections: true
    smooth-scroll: true
    code-copy: true

execute:
  enabled: false    # 不重新执行，使用 Notebook 中已有的输出
